FROM ghcr.io/loong64/manylinux_2_38_loongarch64:2026.06.04-1 AS base

# Language variabes
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# Installed needed OS packages. This is to support all
# the binary builds (torch, vision, audio, text, data)
RUN yum install -y \
  autoconf \
  automake \
  bison \
  bzip2 \
  ccache \
  curl \
  diffutils \
  file \
  git \
  less \
  libffi-devel \
  libgomp \
  make \
  openssl-devel \
  patch \
  perl \
  unzip \
  util-linux \
  wget \
  which \
  xz \
  yasm \
  zstd \
  sudo \
  && \
  yum clean all

# Clang
# ARG RUNNER_ARCH
# RUN [ -n "${RUNNER_ARCH}" ] && manylinux-install-clang

# git236+ would refuse to run git commands in repos owned by other users
# Which causes version check to fail, as pytorch repo is bind-mounted into the image
# Override this behaviour by treating every folder as safe
# For more details see https://github.com/pytorch/pytorch/issues/78659#issuecomment-1144107327
RUN git config --global --add safe.directory "*"

FROM base AS openblas
# Install openblas
# ARG OPENBLAS_VERSION
ADD ./common/install_openblas.sh install_openblas.sh
RUN bash ./install_openblas.sh && rm install_openblas.sh

FROM base AS final
COPY --from=openblas     /opt/OpenBLAS/  /opt/OpenBLAS/
ENV LD_LIBRARY_PATH=/opt/OpenBLAS/lib:$LD_LIBRARY_PATH

ADD repair_manylinux_2_38.sh /usr/local/bin/repair_manylinux_2_38.sh
