name: custom build

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'Build version'
        required: true
        default: ''

jobs:
  custom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        DESIRED_PYTHON: ["3.10", "3.11", "3.12", "3.13", "3.13t", "3.14", "3.14t"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: pytorch/pytorch
          ref: ${{ inputs.app_version }}
          submodules: true

      - name: Prepare build
        run: |
          app_version=${{ inputs.app_version }}
          wget -qO - https://github.com/loong64/pytorch/raw/refs/heads/main/patch_loong64.patch | patch -p1

          wget -qO - https://github.com/loong64/pytorch/raw/refs/heads/main/patch_loong64.patch | patch -p1

          cd third_party/sleef
          wget -qO - https://github.com/loong64/pytorch/raw/refs/heads/main/sleef/sleef_loong64.patch | patch -p1
          cd -

          cd third_party/cpuinfo
          wget -qO - https://github.com/loong64/pytorch/raw/refs/heads/main/cpuinfo/cpuinfo_loong64.patch | patch -p1
          cd -

          echo "PYTORCH_BUILD_NUMBER=1" >> $GITHUB_ENV
          echo "PYTORCH_BUILD_VERSION=${app_version/v/}" >> $GITHUB_ENV
          echo "PIP_EXTRA_INDEX_URL=https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple" >> $GITHUB_ENV

          mkdir -p wheelhouse
          chmod +x .ci/manywheel/build.sh

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Build wheels
        env: 
          PYTORCH_ROOT: /pytorch
          PACKAGE_TYPE: manywheel
          DESIRED_CUDA: cpu
          GPU_ARCH_TYPE: cpu-loongarch64
          DOCKER_IMAGE: ghcr.io/loong64/manylinuxloongarch64-builder:cpu-loongarch64
          DOCKER_IMAGE_TAG_PREFIX: cpu-loongarch64
          DESIRED_PYTHON: "${{ matrix.DESIRED_PYTHON }}"
          BUILD_ENVIRONMENT: linux-loongarch64-binary-manywheel-clang
          PYTORCH_FINAL_PACKAGE_DIR: /artifacts
          PIP_EXTRA_INDEX_URL: "https://gitlab.com/api/v4/projects/65746188/packages/pypi/simple"
        run: |
          DOCKER_CMD="${PYTORCH_ROOT}/.ci/manywheel/build.sh"
          docker run --rm \
            -e PYTORCH_ROOT \
            -e PACKAGE_TYPE \
            -e DESIRED_CUDA \
            -e GPU_ARCH_TYPE \
            -e SKIP_ALL_TESTS=1 \
            -e DESIRED_PYTHON \
            -e BUILD_ENVIRONMENT \
            -e PYTORCH_FINAL_PACKAGE_DIR \ 
            -e PIP_EXTRA_INDEX_URL \
            -v $(pwd):${PYTORCH_ROOT} \
            -v $(pwd)/wheelhouse:/${PYTORCH_FINAL_PACKAGE_DIR} \
          ${DOCKER_IMAGE} \
          sh -c "${DOCKER_CMD}"

      - name: Upload wheels
        run: |
          pip install twine==6.0.1
          for file in wheelhouse/*.whl; do
            twine upload --repository-url https://gitlab.com/api/v4/projects/65746188/packages/pypi $file || true
          done
        env:
          TWINE_USERNAME: ${{ github.repository_owner }}
          TWINE_PASSWORD: ${{ secrets.GL_TOKEN }}

      - name: Upload release
        run:
          gh release upload ${{ needs.check.outputs.version }} -R ${{ github.repository }} wheelhouse/*.whl --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}